version: "3.8"

services:
  master:
    build: .
    command: ./services.sh
    container_name: master
    ports:
      - "22"
    volumes:
      - "hamachi:/var/lib/logmein-hamachi"
    privileged: true
    network_mode: "host"

volumes:
  hamachi: null
