version: "3.8"

services:
  main:
    build: .
    command: ./start-main.sh ${NET_NAME} ${NET_PASS}
    container_name: main
    privileged: true
    network_mode: "host"
    volumes:
      - "hamachi:/var/lib/logmein-hamachi"

  worker:
    build: .
    command: ./start-worker.sh
    container_name: worker
    privileged: true
    network_mode: "host"
    volumes:
      - "hamachi-worker:/var/lib/logmein-hamachi"

volumes:
  hamachi: null
  hamachi-worker: null
