version: "3.8"

services:
  worker:
    build: .
    command: ./init.sh
    container_name: worker
    privileged: true
    network_mode: "host"
    volumes:
      - "worker:/var/lib/logmein-hamachi"
    environment:
      - NET_NAME=${NET_NAME}
      - NET_PASS=${NET_PASS}
      - NET_MODE=${NET_MODE}

volumes:
  worker: null
